language: go
go:
  - 1.5
git:
  submodules: false
before_install:
  - openssl aes-256-cbc -K $encrypted_27d12ea690ba_key -iv $encrypted_27d12ea690ba_iv -in travis-key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - go get -v github.com/spf13/hugo
  - git config --global user.name "Travis CI"; git config --global user.email "decker.christian+travis@gmail.com"
script:
  - make deploy
